# Generated by Django 4.0.4 on 2022-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
